### ISSUE TITLE
Greetings, I have a problem executing the extension.

### ISSUE THREAD

**Issue by Undernoct** [mplatt/virtual-u2f#2]
Greetings, I have followed all the steps and I am trying to put it to work with facebook, since I am a Social marketer and to keep my profiles safer and more comfortable to manage it would be feasible to use it, but when configuring it and pressing the button Simulate touch, does not trigger any code or anything, I would like to know if it is that you can not simulate this hardware nowadays.

**Greetings.**

**Comment by mplatt** [comment]
I'm afraid this project is no longer maintained or updated. It is also not intended to be a replacement for an actual hardware token. Have a look at [some of the forks](https://github.com/mplatt/virtual-u2f/network). Maybe there is something there that works for you.
